name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK (Java 11 in this case)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Cache Maven dependencies to speed up the build process
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run Maven build (compile, test, package)
    - name: Build with Maven
      run: mvn clean install

    # Optionally, deploy or push artifacts to a repository (e.g., Maven Central)
    # - name: Deploy to Maven Central
    #   run: mvn deploy -DskipTests
