name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch
      
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
       fetch-depth: 0
       ref: ${{ github.ref_name}}

    - name: create config path
      run: |
       echo "create config path folder:"
       mkdir '${{github.workspace}}/config'
       echo "create temp folder"
       mkdir '${{github.workspace}}/Tempfolder'

    # Set up JDK (Java 11 in this case)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'
        
    - name: verify java version
      #run: java --version

    # Cache Maven dependencies to speed up the build process
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Run Maven build (compile, test, package)
    - name: Build with Maven
      run: mvn clean install

    # Optionally, deploy or push artifacts to a repository (e.g., Maven Central)
    # - name: Deploy to Maven Central
    #   run: mvn deploy -DskipTests
